# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: A Pastor's Notebook
email: dan@apastorsnotebook.com
description: > # this means to ignore newlines until "baseurl:"
  Faith, politics, cookies
baseurl: "/project" # the subpath of your site, e.g. /blog
url: "pastordan.github.io" # the base hostname & protocol for your site
twitter_username: pastordan
facebook_username: DanielSchultzWriter

# Build settings
highlighter: rouge

#gems
gems: [jekyll-paginate]

#pagination
paginate: 5
safe: false
